### ISSUE TITLE
From Developer: I'm droping support for angular 2

### ISSUE THREAD

**Issue by sheikalthaf** [sheikalthaf/ngx-carousel#26]
Hello everyone,
I'm droping support for angular v2 due to below reason.
Angular 5 version going to release within couple of days. From this version the `renderer` is removed Instead `Renderer2` will be available which is introduced in v4. This change is for angular universal support.
I don't know how many of you using this carousel in v2 but most of the people already using v4 including me. If anyone using v2 please comment below. based on the commands i will work on v2 too

Thanks for your love and support

**Comment by dalvarezr** [comment]
With this new implementation of angular universal support are we going to be able to use this package with a server side rendering configuration? 
If so when would we see a release of your package to support this new version of angular?

**Comment by CanKattwinkel** [comment]
@sheikalthaf I'm currently considering ngx-carousel for a project that uses Angular Universal. Do you already know what kind of server-side rendering limitations currently exist? How will the integration of hammerjs be handled?

**Comment by Renader** [comment]
I'm currently receiving an error when I want to run my universal application on firebase
```

Error: Error occurred while parsing your function triggers.

/tmp/fbfn_2688hWWnMRqgekX4/node_modules/ngx-carousel/src/ngx-item/ngx-item.component.js:1
(function (exports, require, module, __filename, __dirname) { import { Component } from '@angular/core';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.0tz6 (/tmp/fbfn_2688hWWnMRqgekX4/dist-server/main.bundle.js:1:20895)
    at n (/tmp/fbfn_2688hWWnMRqgekX4/dist-server/main.bundle.js:1:211)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Does this library align with the [angular package format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit)? Maybe you should use ng-packagr+angular cli to provide a simpler start for potentially contributors.

**Comment by G1itcher** [comment]
Any update on this? Does this plugin support Universal/will support Universal soon? Working on a new project and would ideally like to avoid reinventing the wheel(carousel)

**Comment by sheikalthaf** [comment]
I tried the carousel with this https://angular.io/guide/universal demo. carousel works fine. Didn't tried with the real-world app. soon i will share more information

**Comment by sheikalthaf** [comment]
@CanKattwinkel https://github.com/angular/universal-starter this link has the details about the universal support.

**Comment by sheikalthaf** [comment]
@dalvarezr @CanKattwinkel @Renader @G1itcher 
Finally **Angular Universal** support
Why I created another repo because of most of the user still in angular 2. So it is difficult to add universal support in this repository.
I have cloned this carousel with universal support in another repository [ngu-carousel](https://github.com/sheikalthaf/ngu-carousel).
In npm [@ngu/carousel](https://www.npmjs.com/package/@ngu/carousel)
With this package, I have updated to `renderer2` to support **Angular Universal**.
In future, this package will be maintained

**Comment by CanKattwinkel** [comment]
@sheikalthaf 

Are you sure, that most of the users are still on Angular 2? In my opinion a fork and the associated segmentation at this time is not advantageous. People depending on Angular 2 should use an old version of ngx carousel. If you want you could even align with the semantic versioning of Angular in order to give better overview. 

Also I couldn't integrate your `@ngu/carousel` into my SSR project. Since you import hammerjs - at least in the version that is published under npm (1.3.3).  NOT in the [Github source](https://github.com/sheikalthaf/ngu-carousel/blob/master/src/ngu-carousel/ngu-carousel.component.ts).


`import * as Hammer from 'hammerjs';`

in `node_modules/@ngu/carousel/src/ngu-carousel/ngu-carousel.component.js`


This obviously causes my node server to fail since no hammerjs is available on server side. So I highly recommend to integrate the ngu changes into this package and to fix the hammerjs imports. The Github source looks good to me, alternatevly you can take a look at how Material 2 handles the (optional) hammerjs import.


Additional types:
https://github.com/angular/material2/blob/0834a31d03ae6707633e01d43200703840b70c5a/src/lib/core/gestures/gesture-annotations.ts

Save access to hammerjs:
https://github.com/angular/material2/blob/0834a31d03ae6707633e01d43200703840b70c5a/src/lib/core/gestures/gesture-config.ts

**Comment by iamlothian** [comment]
That is a good point.

**Comment by CanKattwinkel** [comment]
@sheikalthaf and @iamlothian any news on this issue? I want to release a project by the end of next month and currently only the carousel is blocking my universal build since it requires hammerjs directly. 

Imho you should bump **this** project to version 5.0.0 and do the breaking change of removing renderer. Also you should remove all direct references to hammerjs in sourcecode. At places where you might need `document` you can inject it [like this](https://github.com/crisbeto/material2/commit/ec0df1a249720d30626d4a62ae43e885f2970e73) or just wrap it into if statements. 

To support legacy versions of Angular you can simply create a branch 1.3.x and do bugfix releases there. Parallel distribution of multiple versions is no problem for NPM, the angular cli team works similarly ( Master represents the recent development stand which is currently 1.6.rc, also there are  Branches for 1.3,1.4,1.5 in order to provide bugfixes for older versions).

**Comment by sheikalthaf** [comment]
@CanKattwinkel updated the `@ngu/carousel` to make hammerjs as optional dependency v.1.3.4
hope this version will fix your problem and also updated the repo

**Comment by CanKattwinkel** [comment]
I just wanted to mention that with the version you released, there are no more problems with the Universal Build. 

So thank you very, very much.


However, I would like to add that I would recommend adapting the semver procedure of Angular and to release a 5.0.0 version of ngx-carousel which also includes the changes for ngu-carousel. Because that's what all Angular libraries are going to do, and what really gives developers a safe way of working. 

Also a version 5.0.0 does not mean you can't back-port changes from 5. x. x to 'older' versions appearing in e.g. the 1.3.x branch - which can continue to support Angular < 4.
