### ISSUE TITLE
Nested carousels

### ISSUE THREAD

**Issue by iamlothian** [sheikalthaf/ngx-carousel#42]
I noticed two issues when nesting carousels, which was likely not an intended feature, but i believe it to be possible.

1. It seems as though the nested carousel picks up the [input] value of the parent carousel rather than using its own. In my case (Which i will attempt to reproduce in an isolated sample) An outer Tile carousel causes and inner item carousel to become tiles and use the same grid definition.

2. touch events are propagated from the nested carousel to the parent resulting in both handling the scroll touch events.

EDIT: as promised [Plunker](https://plnkr.co/edit/IeXFBqMrsBW0QHKHa6JY?p=preview)

**Comment by sheikalthaf** [comment]
Nice suggestion.
In your first point the nested carousel doesn't picks input of the parent. 
In my carousel css i'm point the item selector as `autogenerated id and .item` class. 
but css taking parent autogenerated id and child .tem class,  Due to this the parent css applied to the child carousel. **This issue will be fixed in next update.**
Second point:
don't have any idea how to solve this

**Comment by sheikalthaf** [comment]
I need help to solve this issue #20 . Do you know how to solve this issue. It's all about **hammerjs**

**Comment by iamlothian** [comment]
I'll try have a look at this.

**Comment by sheikalthaf** [comment]
@iamlothian thanks for helping to fix issues. read the changelog file
